### ISSUE TITLE
CI tests fail but the travis build is a success

### ISSUE THREAD

**Issue by fazo96** [ChluNetwork/chlu-demo#22]
Check this: https://travis-ci.org/ChluNetwork/chlu-demo/builds/324500476?utm_source=github_status&utm_medium=notification

It looks like even though a lot of tests are failing the process returns zero so travis thinks everything is ok. I don't know why this happens, but most tests fail due to outdated snapshots.

**Comment by kulpreet** [comment]
@Venumteam Do you want to see what is happening here?
