### ISSUE TITLE
Replace placeholders with ChluIPFS calls

### ISSUE THREAD

**Issue by fazo96** [ChluNetwork/chlu-demo#24]
I opened this to track progress in integrating the chlu-ipfs-support library in chlu-demo.

Here is a list with all the places where ChluIPFS should be called in the code as far as I know:

- [x] when a payment is made
  -  [ ] currently creates a review record with placeholder data
- [ ] in vendor profile and wallet to read reviews
- [ ] in customer transactions page to read previously left reviews and/or update them

Other things we have to figure out:

- the demo has a vendor and customer part but ChluIPFS can only be started in customer or vendor mode. When we switch mode in the UI, ChluIPFS should be restarted
- ~~the UI does not wait for ChluIPFS to be ready. This could cause a race condition when the API is called before it's ready~~ #25 

The current implementation is in the ipfs branch

**Comment by kulpreet** [comment]
@fazo96 we should definitely resolve "the UI should wait for IPFS" to be ready part. Let's create a separate issue for it and use the ipfs-integration label

**Comment by kulpreet** [comment]
@fazo96 - about the vendor/customer ipfs modes, ideally we shouldn't kill all libp2p connections and reconnect if a user switches from vendor to customer and vice versa. Can we switch modes while still using the same js-ipfs instance? Maybe this is a separate issue as well?

**Comment by fazo96** [comment]
> about the vendor/customer ipfs modes, ideally we shouldn't kill all libp2p connections and reconnect if a user switches from vendor to customer and vice versa. Can we switch modes while still using the same js-ipfs instance? Maybe this is a separate issue as well?

Yes, this makes a lot of sense. At the moment if you stop the node, switch type manually and start it again it kills all connections because it restarts the underlying ipfs node. A `switchType` API should do the job without restarting IPFS under the hood.

However I see there is a Demonstrator mode in the demo that shows both the customer payment and the vendor wallet pages. How would this work? We would need to either run two different ChluIPFS instances or use two browser tabs instead for this use case

**Comment by fazo96** [comment]
Here's the PR with the switchType API call implementation in chlu-ipfs-support: https://github.com/ChluNetwork/chlu-ipfs-support/pull/14

**Comment by fazo96** [comment]
Closing this since we removed all test data related to Reviews/IPFS
