### ISSUE TITLE
As a customer, once I have created a wallet the "create wallet" button disappear

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-demo#31]
This will allow the customer to go the to the wallet only if they have copied or downloaded the mnemonic.

As a consequence, we should show a new button "Go to Wallet" once the mnemonic has been downloaded.

- [x] Hide "Create wallet" once wallet is created and instead show a message "Please save your mnemonic. Once you have saved it you will be able to access the wallet"
- [x] Keep "Create wallet" till the user either clicks "copy mnemonic" or "download mnemonic"
- [x] Once either of the buttons are clicked, show new button saying "Go to wallet" which takes the user to the new wallet.

**Comment by fazo96** [comment]
@kp Looks like this is already implemented in master, should I close the issue?
