### ISSUE TITLE
Loading /vendor/wallet is throwing an error

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-demo#33]
![image](https://user-images.githubusercontent.com/13216/34983724-b951d942-faae-11e7-8de4-5eb79ec6de10.png)

**Comment by Venumteam** [comment]
@kulpreet try to remove please `chlu-wallet-support` from the node-modules and then run `yarn add https://github.com/ChluNetwork/chlu-wallet-support-js.git` then it should work. You can see that error pointed out to the old dependency but not to our fork
