### ISSUE TITLE
WithChlu state not changing to ready

### ISSUE THREAD

**Issue by kulpreet** [ChluNetwork/chlu-demo#51]
Maybe it is a problem on my machine today, but the spinner doesn't go away, and the getChluIPFS
![screen shot 2018-02-17 at 07 53 25](https://user-images.githubusercontent.com/13216/36337222-acc10b40-13b7-11e8-8f1e-b115f253737b.png)

For now, I am changing the state to true in the constructor, then I see the form and can put objects to IPFS

**Comment by fazo96** [comment]
Judging from the logs in the screenshot it looks like it could not connect to a service node. I'll see if I can figure out why

**Comment by fazo96** [comment]
@kulpreet I don't think this is relevant anymore, so I am closing it
